// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestWeb_NguyenHoangPhu.Models;

namespace TestWeb_NguyenHoangPhu.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250612073732_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestWeb_NguyenHoangPhu.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Microsoft",
                            Price = 10.99m,
                            Quantity = 100,
                            Title = "ASP.NET Core"
                        },
                        new
                        {
                            Id = 2,
                            Author = "EF Team",
                            Price = 12.99m,
                            Quantity = 50,
                            Title = "Entity Framework Core"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Mark J. Price",
                            Price = 15.49m,
                            Quantity = 80,
                            Title = "C# Fundamentals"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Sheep",
                            Price = 10.29m,
                            Quantity = 65,
                            Title = "Sleep"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
